NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
bmi <- subset(NEI, fips == "24510", select = c(Emissions, year))
bmiSub <- aggregate(bmi$Emissions,list(Year = bmi$year), sum)
with(bmiSub,plot(Year,x, type ="l",xlab = "year", ylab = "Total Emissions in Baltimore", main = "Total Emissions in Baltimore by year"))
dev.copy(png, file = "plot2") 
dev.off()