ihpc <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", nrows = 100 )
classes <- sapply(ihpc, class)
hpc <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?", colClasses = classes, nrows = 2075259)
shpc <- subset( hpc, Date == "2/2/2007"|Date == "1/2/2007" )
D_T <- paste (shpc$Date, shpc$Time)
D_T <- strptime(D_T, "%d/%m/%Y %H:%M:%S")
png(file="plot2")
plot(D_T, shpc$Global_active_power, type ="l", xlab="", ylab = "Global Active Power (kilowatts)")
dev.off()
