NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
NEI<- transform(NEI, year = factor(NEI$year))
totalSub <- aggregate(NEI$Emissions,list(Year = NEI$year), sum)
plot(totalSub$x, totalSub$year, xlab = "year", ylab = "TotalEmissions", main = "total PM2.5 emission by year")
dev.copy(png, file = "plot1.png") 
dev.off()