NEI <- readRDS("summarySCC_PM25.rds")
NEI<- transform(NEI, year = factor(NEI$year))
SCC <- readRDS("Source_Classification_Code.rds")
combCoal <- unique(SCC$EI.Sector)[c(1,6,11)]
ccSCC <- subset(SCC, EI.Sector %in% combCoal, SCC)
ccNEI <- subset(NEI, NEI$SCC %in% ccSCC$SCC, c(Emissions,year) )
emiperyear <- aggregate(ccNEI$Emissions, list(Year = ccNEI$year), sum)
ggplot(emiperyear, aes(Year, x)) +geom_line(aes(group = rep(1,4))) +geom_point() + ggtitle("Total Emissions of Coal Combustion-Related Sources by Year") + xlab("year") +ylab("Total Emissions")
dev.copy(png, file = "plot4.png")
dev.off()
