ihpc <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", nrows = 100 )
classes <- sapply(ihpc, class)
hpc <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?", colClasses = classes, nrows = 2075259)
shpc <- subset( hpc, Date == "2/2/2007"|Date == "1/2/2007" )
D_T <- paste (shpc$Date, shpc$Time)
D_T <- strptime(D_T, "%d/%m/%Y %H:%M:%S")
nhpc <- cbind(shpc, D_T)
png(file = "plot4")
par(mfcol=c(2,2), mar=c(4,4,4,4))
with(nhpc,plot(D_T, Global_active_power, type = "l", xlab ="", ylab= "Global Active Power"))
with(nhpc,plot(D_T,Sub_metering_1, type ="l",xlab="",ylab="Energy sub metering"))
with(nhpc,points(D_T,Sub_metering_2, type ="l", col="red"))
with(nhpc,points(D_T,Sub_metering_3, type ="l", col="blue"))
legend("topright", pch = "-", col = c("black","red","blue"), legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),cex=0.8)
with(nhpc,plot(D_T, Voltage, type = "l", xlab ="datetime", ylab= "Voltage"))
with(nhpc,plot(D_T, Global_reactive_power, type = "l", xlab ="datetime", ylab= "Global_reactive_power"))
dev.off()